# General settings
seed: 42
device: cuda
log_dir: logs/
checkpoint_dir: checkpoints/
results_dir: results/

# Dataset settings
dataset:
  name: GOOD-Cora
  path: data/
  domain: degree
  shift: covariate
  generate: False

# Model settings
model:
  type: gin  # gin, gcn, sage
  hidden_channels: 64
  num_layers: 3
  dropout: 0.5
  num_experts: 1  # Set to 1 for baseline, increase for MoE
  
# MoE settings (for stages beyond baseline)
moe:
  enabled: False
  gating: uniform  # uniform, soft_attention, learned_voting
  diversity_loss: False
  diversity_weight: 0.1
  
# Augmentation settings
augmentation:
  enabled: False
  strategy: none  # none, node_masking, edge_perturbation, learned
  expert_specific: False
  
# Meta-regularization
meta_regularization:
  enabled: False
  type: none  # none, contrastive, info_max
  weight: 0.1

# Training settings
training:
  lr: 0.001
  epochs: 100
  batch_size: 32
  early_stopping: 20
  optimizer: adam 