# Main configuration file for GNN experiments

# Experiment settings
experiment:
  name: "moe_sst2" # baseline_gnn or moe_nogate_noaug or moe_noaug
  device: "cuda"  # or "cpu"
  debug:
    enable: false
    num_samples: 512
    epochs: 50
    verbose: false
  seeds: [1, 2, 3, 4, 5]  # Add more seeds as needed
  hyper_search:
    enable: false
    n_trials_1: 10
    n_trials_2: 5
    test_after: true

# Dataset configuration
dataset:
  dataset_name: "GOODSST2"  # Specific dataset from GOOD
  task_type: "graph_classification"
  path: "./datasets"
  shift_type: "covariate" # covariate, concept, no_shift
  batch_size: 64
  num_workers: 4
  domain: 'length'

# Model configuration
model:
  type: "moe"  # Options: GIN, GCN, GraphSAGE, moe
  parallel: false
  hidden_dim: 300
  num_layers: 3
  dropout: 0.5
  global_pooling: "sum"  # Options: mean, sum, max
  weight_str: 0.0 # best 0.1
  weight_la: 0.0 # best 0.1
  weight_ea: 0.0 # best 0.1
  weight_reg: 1.0
  weight_ce: 1.0
  weight_div: 1.0
  weight_load: 0.5
  num_experts: 1
  aggregation: "weighted_mean"  # Options: mean, majority_vote, weighted_mean
  adv_warmup_epochs: 2 # best 2
  adv_ramp_epochs: 4
  strinv_warmup_epochs: 1
  strinv_ramp_epochs: 1
  rho_edge: 0.2 # best 0.2 or 0.9

# Training configuration
training:
  epochs: 30 # BEST 30
  lr: 0.001
  weight_decay: 0.0001
  early_stopping:
    patience: 20
    min_delta: 0.001

# Logging configuration
logging:
  wandb:
    enable: false
    project: "graph_moe_ood"
    entity: "jhsun163-university-of-toronto"
  log_interval: 10
  save_model: true

# Gating module configuration
gate:
  activation: "entmax"
  entmax_alpha: 0.99
  model: "GIN"
  depth: 2
  hidden_dim: 64
  train_after: 10
  finetune_epochs: 0