# Main configuration file for GNN experiments

# Experiment settings
experiment:
  name: "DEBUG" # baseline_gnn or moe_nogate_noaug or moe_noaug
  device: "cuda"  # or "cpu"
  debug:
    enable: true
    num_samples: 64
    epochs: 3
    verbose: false
  seeds: [42]  # Add more seeds as needed
  hyper_search:
    enable: false
    n_trials: 2
    test_after: true

# Dataset configuration
dataset:
  dataset_name: "GOODMotif"  # Specific dataset from GOOD
  task_type: "graph_classification"
  path: "./datasets"
  shift_type: "covariate" # covariate, concept, no_shift
  batch_size: 32
  num_workers: 4
  domain: "size"

# Model configuration
model:
  type: "moe"  # Options: GIN, GCN, GraphSAGE, moe
  parallel: false
  hidden_dim: 64
  num_layers: 3
  dropout: 0.5
  pooling: "mean"  # Options: mean, sum, max
  weight_str: 1.0
  weight_la: 1.0
  weight_ea: 1.0
  weight_reg: 1.0
  weight_ce: 1.0
  weight_div: 1.0
  weight_load: 1.0
  num_experts: 3
  aggregation: "weighted_mean"  # Options: mean, majority_vote, weighted_mean3
  adv_warmup_epochs: 1
  adv_ramp_epochs: 0
  str_warmup_epochs: 2
  str_ramp_epochs: 5


# Training configuration
training:
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Logging configuration
logging:
  wandb:
    enable: false
    project: "graph_moe_ood"
    entity: "jhsun163-university-of-toronto"
  log_interval: 10
  save_model: true

# Gating module configuration
gate:
  activation: "entmax"
  entmax_alpha: 1.1
  model: "GIN"
  depth: 2
  hidden_dim: 32
  train_after: 2