# Main configuration file for GNN experiments

# Experiment settings
experiment:
  name: "moe_nogate_noaug" # baseline_gnn or moe_nogate_noaug
  seed: 42
  device: "cuda"  # or "cpu"
  debug:
    enable: true
    num_samples: 1024
    epochs: 50

# Dataset configuration
dataset:
  dataset_name: "GOODCMNIST"  # Specific dataset from GOOD
  task_type: "graph_classification"
  path: "./datasets"
  shift_type: "covariate" # covariate, concept, no_shift
  batch_size: 16
  num_workers: 4

# Model configuration
model:
  type: "moe"  # Options: GIN, GCN, GraphSAGE, moe
  hidden_dim: 64
  num_layers: 3
  dropout: 0.5
  pooling: "mean"  # Options: mean, sum, max

# MoE specific configuration
moe:
  num_experts: 4
  aggregation: "mean"  # Options: mean, majority_vote

# Training configuration
training:
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Logging configuration
logging:
  wandb:
    enable: true
    project: "graph_moe_ood"
    entity: "jhsun163-university-of-toronto"
  log_interval: 10
  save_model: true 