# Main configuration file for GNN experiments

# Experiment settings
experiment:
  name: "moeuil_diverse_sparse_8exp" # baseline_gnn or moe_nogate_noaug or moe_noaug
  device: "cuda"  # or "cpu"
  debug:
    enable: false
    num_samples: 512
    epochs: 50
    verbose: false
  seeds: [1,2,3]  # Add more seeds as needed

# Dataset configuration
dataset:
  dataset_name: "GOODCMNIST"  # Specific dataset from GOOD
  task_type: "graph_classification"
  path: "./datasets"
  shift_type: "covariate" # covariate, concept, no_shift
  batch_size: 64
  num_workers: 4

# Model configuration
model:
  type: "moe_uil"  # Options: GIN, GCN, GraphSAGE, moe, moe_uil, uil
  parallel: false
  hidden_dim: 64
  num_layers: 3
  dropout: 0.5
  pooling: "mean"  # Options: mean, sum, max
  weight_str: 0.0
  weight_sem: 1.0
  weight_reg: 1.0
  weight_ce: 1.0
  weight_div: 1.0
  weight_load: 1.0
  num_experts: 8
  aggregation: "weighted_mean"  # Options: mean, majority_vote, weighted_mean


# Training configuration
training:
  epochs: 100
  lr: 0.001
  weight_decay: 0.0001
  early_stopping:
    patience: 10
    min_delta: 0.001

# Logging configuration
logging:
  wandb:
    enable: false
    project: "graph_moe_ood"
    entity: "jhsun163-university-of-toronto"
  log_interval: 10
  save_model: true

# Gating module configuration
gate:
  activation: "entmax"
  entmax_alpha: 1.3
  model: "GIN"
  depth: 2
  hidden_dim: 64
  train_after: 10